# Projeto Python IA: Inteligência Artificial e Previsões

### Case: Score de Crédito dos Clientes

Você foi contratado por um banco para conseguir definir o score de crédito dos clientes. Você precisa analisar todos os clientes do banco e, com base nessa análise, criar um modelo que consiga ler as informações do cliente e dizer automaticamente o score de crédito dele: Ruim, Ok, Bom

Arquivos da aula: https://drive.google.com/drive/folders/1FbDqVq4XLvU85VBlVIMJ73p9oOu6u2-J?usp=drive_link

In [5]:
#!pip install scikit-learn
# !python.exe -m pip install --upgrade pip 

# Entender o desafio
# Importar dados

import pandas 

tabela = pandas.read_csv("clientes.csv")
display(tabela)

,id_cliente,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,...,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,score_credito,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,3392,1,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,265.0,21.465380,alto_gasto_pagamento_baixos,312.494089,Good,1,1,1,1,0
1,3392,2,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,266.0,21.465380,baixo_gasto_pagamento_alto,284.629162,Good,1,1,1,1,0
2,3392,3,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,267.0,21.465380,baixo_gasto_pagamento_medio,331.209863,Good,1,1,1,1,0
3,3392,4,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,5.0,...,268.0,21.465380,baixo_gasto_pagamento_baixo,223.451310,Good,1,1,1,1,0
4,3392,5,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,6.0,...,269.0,21.465380,alto_gasto_pagamento_medio,341.489231,Good,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,37932,4,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,23.0,...,378.0,24.028477,alto_gasto_pagamento_alto,479.866228,Poor,1,0,0,0,1
99996,37932,5,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,18.0,...,379.0,24.028477,alto_gasto_pagamento_medio,496.651610,Poor,1,0,0,0,1
99997,37932,6,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,27.0,...,380.0,24.028477,alto_gasto_pagamento_alto,516.809083,Poor,1,0,0,0,1
99998,37932,7,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,20.0,...,381.0,24.028477,baixo_gasto_pagamento_alto,319.164979,Standard,1,0,0,0,1
99999,37932,8,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,18.0,...,382.0,24.028477,alto_gasto_pagamento_medio,393.673696,Poor,1,0,0,0,1

In [6]:
print(tabela.info())
""" float: números com casas decimais
int: números sem casas decimais
object: string """

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_cliente                100000 non-null  int64
 1   mes                       100000 non-null  int64
 2   idade                     100000 non-null  float64
 3   profissao                 100000 non-null  object
 4   salario_anual             100000 non-null  float64
 5   num_contas                100000 non-null  float64
 6   num_cartoes               100000 non-null  float64
 7   juros_emprestimo          100000 non-null  float64
 8   num_emprestimos           100000 non-null  float64
 9   dias_atraso               100000 non-null  float64
 10  num_pagamentos_atrasados  100000 non-null  float64
 11  num_verificacoes_credito  100000 non-null  float64
 12  mix_credito               100000 non-null  object
 13  divida_total              100000 non-null  float64
 14  taxa_uso_credito          100000 non-null  float64
 15  idade_historico_credito   100000 non-null  float64
 16  investimento_mensal       100000 non-null  float64
 17  comportamento_pagamento   100000 non-null  object
 18  saldo_final_mes           100000 non-null  float64
 19  score_credito             100000 non-null  object
 20  emprestimo_carro          100000 non-null  int64
 21  emprestimo_casa           100000 non-null  int64
 22  emprestimo_pessoal        100000 non-null  int64
 23  emprestimo_credito        100000 non-null  int64
 24  emprestimo_estudantil     100000 non-null  int64
dtypes: float64(14), int64(7), object(4)
memory usage: 19.1+ MB
None

' float: números com casas decimais\nint: números sem casas decimais\nobject: string '

In [7]:
# Preparar base de dados (pré processamento)
# IA NÃO APRENDE COM OBJECT, SÓ PODE TER OBJECT NO RETORNO DE RESPOSTA
# profissão, mix-credito, comportamento-pagamento
# label enconder = colocar rótulo em cada valor
from sklearn.preprocessing import LabelEncoder # importa só a função que você quer

codificador = LabelEncoder()
tabela["profissao"] = codificador.fit_transform(tabela["profissao"]) # o valor será substituído pela transformação
tabela["mix_credito"] = codificador.fit_transform(tabela["mix_credito"])
tabela["comportamento_pagamento"] = codificador.fit_transform(tabela["comportamento_pagamento"]) 
print(tabela.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_cliente                100000 non-null  int64
 1   mes                       100000 non-null  int64
 2   idade                     100000 non-null  float64
 3   profissao                 100000 non-null  int64
 4   salario_anual             100000 non-null  float64
 5   num_contas                100000 non-null  float64
 6   num_cartoes               100000 non-null  float64
 7   juros_emprestimo          100000 non-null  float64
 8   num_emprestimos           100000 non-null  float64
 9   dias_atraso               100000 non-null  float64
 10  num_pagamentos_atrasados  100000 non-null  float64
 11  num_verificacoes_credito  100000 non-null  float64
 12  mix_credito               100000 non-null  int64
 13  divida_total              100000 non-null  float64
 14  taxa_uso_credito          100000 non-null  float64
 15  idade_historico_credito   100000 non-null  float64
 16  investimento_mensal       100000 non-null  float64
 17  comportamento_pagamento   100000 non-null  int64
 18  saldo_final_mes           100000 non-null  float64
 19  score_credito             100000 non-null  object
 20  emprestimo_carro          100000 non-null  int64
 21  emprestimo_casa           100000 non-null  int64
 22  emprestimo_pessoal        100000 non-null  int64
 23  emprestimo_credito        100000 non-null  int64
 24  emprestimo_estudantil     100000 non-null  int64
dtypes: float64(14), int64(10), object(1)
memory usage: 19.1+ MB
None

In [8]:
# Quais dados vai utilizar (x)
x = tabela.drop(columns = ["id_cliente", "score_credito"]) # a tabela toda, menos essas duas
# Qual coluna tem que prever (y)
y = tabela["score_credito"]
display(x)


from sklearn.model_selection import train_test_split
# DIVIDE OS DADOS EM 4
# Dados X de treino (para a IA treinar e aprender a fazer)
# Dados Y de teste (para ver se a IA aprendeu)

# Dados X de treino (para a IA treinar e aprender a fazer)
# Dados Y de teste (para ver se a IA aprendeu)

x_treino, x_teste, y_treino, y_teste = train_test_split(x, y) # DIVIDE OS DADOS EM TESTE E TREINO

,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,num_pagamentos_atrasados,...,taxa_uso_credito,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,1,23.0,2,19114.12,3.0,4.0,3.0,4.0,3.0,7.0,...,26.822620,265.0,21.465380,1,312.494089,1,1,1,1,0
1,2,23.0,2,19114.12,3.0,4.0,3.0,4.0,3.0,4.0,...,31.944960,266.0,21.465380,3,284.629162,1,1,1,1,0
2,3,23.0,2,19114.12,3.0,4.0,3.0,4.0,3.0,7.0,...,28.609352,267.0,21.465380,5,331.209863,1,1,1,1,0
3,4,23.0,2,19114.12,3.0,4.0,3.0,4.0,5.0,4.0,...,31.377862,268.0,21.465380,4,223.451310,1,1,1,1,0
4,5,23.0,2,19114.12,3.0,4.0,3.0,4.0,6.0,4.0,...,24.797347,269.0,21.465380,2,341.489231,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,4,25.0,11,39628.99,4.0,6.0,7.0,2.0,23.0,7.0,...,34.663572,378.0,24.028477,0,479.866228,1,0,0,0,1
99996,5,25.0,11,39628.99,4.0,6.0,7.0,2.0,18.0,7.0,...,40.565631,379.0,24.028477,2,496.651610,1,0,0,0,1
99997,6,25.0,11,39628.99,4.0,6.0,7.0,2.0,27.0,6.0,...,41.255522,380.0,24.028477,0,516.809083,1,0,0,0,1
99998,7,25.0,11,39628.99,4.0,6.0,7.0,2.0,20.0,6.0,...,33.638208,381.0,24.028477,3,319.164979,1,0,0,0,1
99999,8,25.0,11,39628.99,4.0,6.0,7.0,2.0,18.0,6.0,...,34.192463,382.0,24.028477,2,393.673696,1,0,0,0,1

In [9]:
# Criar modelo de IA, calcular nota de crédito (ruim, ok, bom)
# DOIS MODELOS (A forma como aprende e prevê muda para cada modelo)
""" CRIAR IA
importar a IA
criar a IA
treinar a IA """

"""
- Árvore de decisão (faz perguntas para a base de dados e segue caminhos diferentes conforme a resposta (tipo if/else)) 
- KNN (Vizinhos próximos) (Vai separar a base de dados e vai deduzir a resposta de acordo com o valor do elemento 
mais próximo) 
"""
# importar
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
# criar
modelo_arvoredecisao = RandomForestClassifier()
modelo_knn = KNeighborsClassifier()
# treinar
modelo_arvoredecisao.fit(x_treino, y_treino)
modelo_knn.fit(x_treino, y_treino)

KNeighborsClassifier()

In [10]:
# Escolher o melhor modelo
# Verificar qual acerta mais comparado com o gráfico

previsao_arvoredecisao = modelo_arvoredecisao.predict(x_teste) # PREVER
previsao_knn = modelo_knn.predict(x_teste) # PREVER

from sklearn.metrics import accuracy_score # verificar quantos acertou
# prego cada resultado das previsões que ele fez e comparo fazendo a porcentagem de acerto (comparando com o y_teste)
display(accuracy_score(y_teste, previsao_arvoredecisao)) # 82% (O MELHOR)
display(accuracy_score(y_teste, previsao_knn)) # 74% (Para melhorar os dados: mais ou menos colunas, mais dados, 
#mudar modelo)

0.83004

0.74312

In [19]:
# Usar modelo para fazer previsões
# Importar novos clientes
tabela2 = pandas.read_csv("novos_clientes.csv")
display(tabela2)
# Transformar valores dos dados
tabela2["profissao"] = codificador.fit_transform(tabela2["profissao"]) # o valor será substituído pela transformação
tabela2["mix_credito"] = codificador.fit_transform(tabela2["mix_credito"])
tabela2["comportamento_pagamento"] = codificador.fit_transform(tabela2["comportamento_pagamento"]) 
print(tabela2.info())

# Fazer previsões (usando árvore de decisão)
previsao = modelo_arvoredecisao.predict(tabela2) # passando a tabela toda para prever
display(tabela2)
display(previsao)

,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,num_pagamentos_atrasados,...,taxa_uso_credito,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,1,31.0,empresario,19300.340,6.0,7.0,17.0,5.0,52.0,19.0,...,29.934186,218.0,44.50951,baixo_gasto_pagamento_baixo,312.487689,1,1,0,0,0
1,4,32.0,advogado,12600.445,5.0,5.0,10.0,3.0,25.0,18.0,...,28.819407,12.0,0.00000,baixo_gasto_pagamento_medio,300.994163,0,0,0,0,1
2,2,48.0,empresario,20787.690,8.0,6.0,14.0,7.0,24.0,14.0,...,34.235853,215.0,0.00000,baixo_gasto_pagamento_alto,345.081577,0,1,0,1,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   mes                       3 non-null      int64
 1   idade                     3 non-null      float64
 2   profissao                 3 non-null      int64
 3   salario_anual             3 non-null      float64
 4   num_contas                3 non-null      float64
 5   num_cartoes               3 non-null      float64
 6   juros_emprestimo          3 non-null      float64
 7   num_emprestimos           3 non-null      float64
 8   dias_atraso               3 non-null      float64
 9   num_pagamentos_atrasados  3 non-null      float64
 10  num_verificacoes_credito  3 non-null      float64
 11  mix_credito               3 non-null      int64
 12  divida_total              3 non-null      float64
 13  taxa_uso_credito          3 non-null      float64
 14  idade_historico_credito   3 non-null      float64
 15  investimento_mensal       3 non-null      float64
 16  comportamento_pagamento   3 non-null      int64
 17  saldo_final_mes           3 non-null      float64
 18  emprestimo_carro          3 non-null      int64
 19  emprestimo_casa           3 non-null      int64
 20  emprestimo_pessoal        3 non-null      int64
 21  emprestimo_credito        3 non-null      int64
 22  emprestimo_estudantil     3 non-null      int64
dtypes: float64(14), int64(9)
memory usage: 684.0 bytes
None

,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,num_pagamentos_atrasados,...,taxa_uso_credito,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,1,31.0,1,19300.340,6.0,7.0,17.0,5.0,52.0,19.0,...,29.934186,218.0,44.50951,1,312.487689,1,1,0,0,0
1,4,32.0,0,12600.445,5.0,5.0,10.0,3.0,25.0,18.0,...,28.819407,12.0,0.00000,2,300.994163,0,0,0,0,1
2,2,48.0,1,20787.690,8.0,6.0,14.0,7.0,24.0,14.0,...,34.235853,215.0,0.00000,0,345.081577,0,1,0,1,0

array(['Poor', 'Good', 'Good'], dtype=object)